version: '3.9'
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: projekt_db
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: flask_backend
    depends_on:
      - db
    environment:
      - FLASK_APP=run:app
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=projekt_db
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
#    volumes:
#      - ./frontend:/app